# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VPT-nKd3wHO9Ll0SWcLZdNMmsS4I97bh
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import re
import string

df1 = pd.read_csv("/content/balanced_sentiment_data.csv")
df2 = pd.read_csv("/content/combined_emotion.csv")
df3 = pd.read_csv("/content/combined_sentiment_data.csv")

# Rename to standard format
df1 = df1.rename(columns={'sentence': 'text', 'sentiment': 'label'})
df2 = df2.rename(columns={'sentence': 'text', 'emotion': 'label'})
df3 = df3.rename(columns={'sentence': 'text', 'sentiment': 'label'})

df = pd.concat([df1, df2, df3], ignore_index=True)

df.head()

df.dropna(inplace=True)
df.drop_duplicates(inplace=True)

for col in df.columns:
    print(col)


if 'sentence' in df.columns:
    df.rename(columns={'sentence': 'text'}, inplace=True)
if 'sentiment' in df.columns:
    df.rename(columns={'sentiment': 'label'}, inplace=True)
if 'emotion' in df.columns:
    df.rename(columns={'emotion': 'label'}, inplace=True)

print("Final columns:", df.columns.tolist())


df = df[['text', 'label']]

print("After renaming:", df.columns.tolist())

df.shape, df.columns.tolist(), df.sample(3, random_state=42)

df = df[['text', 'label']]



df = df[df['label'].notnull()]
df['label'] = df['label'].astype(str)
df = df[df['label'].str.strip() != '']
df = df[df['label'].apply(lambda x: isinstance(x, str))]



def clean_text(text):
    text = text.lower()
    text = re.sub(r"http\S+|www\S+|https\S+", '', text)
    text = re.sub(r"@\w+|#\w+", '', text)
    text = re.sub(r"[%s]" % re.escape(string.punctuation), '', text)
    text = re.sub(r"\d+", '', text)
    text = re.sub(r"\s+", ' ', text).strip()
    return text

df['clean_text'] = df['text'].apply(clean_text)

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(10, 6))
sns.countplot(data=df, x='label', order=df['label'].value_counts().index, palette='Set2')
plt.title("Label Distribution (Combined Data)", fontsize=16)
plt.xticks(rotation=45)
plt.tight_layout()
plt.grid(True, linestyle='--', alpha=0.3)
plt.show()

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

X = df['text']
y = df['label']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)



vectorizer = TfidfVectorizer(max_features=3000, stop_words='english', ngram_range=(1, 2))
X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)

from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train_vec, y_train)

model = LogisticRegression(max_iter=200)
model.fit(X_train_vec, y_train)

y_pred = model.predict(X_test_vec)

print(" Accuracy:", accuracy_score(y_test, y_pred))
print("\n Classification Report:\n", classification_report(y_test, y_pred))

cm = confusion_matrix(y_test, y_pred, labels=model.classes_)
plt.figure(figsize=(12, 6))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues", xticklabels=model.classes_, yticklabels=model.classes_)
plt.title("Confusion Matrix")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.tight_layout()
plt.show()

!pip install streamlit -q

import os, json, time, random, gc
from uuid import uuid4
from datetime import datetime, date
from typing import List, Dict, Any



import os, time, random
import streamlit as st
import torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification
from scipy.special import expit


st.set_page_config(page_title="Mental Health Journaling Chatbot", layout="centered")
st.title("Mental Health Journaling Chatbot")

import re
import string


def clean_input(text):
    text = text.lower()
    text = re.sub(r"http\S+|www\S+", "", text)
    text = re.sub(r"@\w+|#\w+", "", text)
    text = re.sub(f"[{re.escape(string.punctuation)}]", "", text)
    text = re.sub(r"\d+", "", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text


def predict_emotion(text_input):
    cleaned = clean_input(text_input)
    vector = vectorizer.transform([cleaned])
    prediction = model.predict(vector)[0]
    return prediction

!pip install -q transformers torch together

from transformers import AutoTokenizer, AutoModelForSequenceClassification
from scipy.special import softmax
import torch

model_name = "cardiffnlp/twitter-roberta-base-emotion"
tokenizer = AutoTokenizer.from_pretrained(model_name)
emotion_model = AutoModelForSequenceClassification.from_pretrained(model_name)

emotion_labels = ['anger', 'joy', 'optimism', 'sadness']

def detect_emotion(text):
    inputs = tokenizer(text, return_tensors="pt", truncation=True, padding=True)
    with torch.no_grad():
        logits = emotion_model(**inputs).logits
    probs = softmax(logits.numpy()[0])
    top_idx = probs.argmax()
    return emotion_labels[top_idx], float(probs[top_idx])



if st.checkbox("Show emotion scores"):
    st.dataframe(
        pd.DataFrame.from_dict(_, orient="index", columns=["score"])
          .sort_values("score", ascending=False)
    )

!pip install together --quiet



def safe_chat_completion(messages, model="meta-llama/Llama-3.3-70B-Instruct-Turbo", max_tokens=300, temperature=0.7, top_p=0.9):
    for attempt in range(5):
        try:
            r = client.chat.completions.create(
                model=model,
                messages=messages,
                max_tokens=max_tokens,
                temperature=temperature,
                top_p=top_p,
            )
            return r.choices[0].message.content.strip()
        except Exception as e:
            s = str(e)
            if "429" in s or "RateLimit" in s or "temporarily unavailable" in s:
                time.sleep((2 ** attempt) + random.uniform(0, 0.5))
                continue
            raise

!pip -q install streamlit

import streamlit as st

@st.cache_resource(show_spinner=False)
def _load_emotion_model():
    ...

st.set_page_config(page_title="Daily Mental Health Chatbot", layout="wide")
st.title("🧠 Daily Mental Health Chatbot")

SAVE_CHATS = "chats.json"
SAVE_CHECKINS = "checkins.csv"

CRISIS_PHRASES = [
    "suicide", "kill myself", "end my life", "self harm", "self-harm",
    "hurt myself", "can't go on", "don't want to live", "ending it"
]

RESOURCES = (
    "**If you’re in immediate danger, call your local emergency number.**\n\n"
    "- 🇺🇸 **988 Suicide & Crisis Lifeline** — call or text **988**, chat via 988lifeline.org\n"
    "- 🌐 **IFRC referral**: ifrc.org/mental-health\n"
    "- 🌐 **Find a helpline (global)**: findahelpline.com\n"
)

!pip -q install torch --extra-index-url https://download.pytorch.org/whl/cpu

def load_chats() -> Dict[str, Any]:
    try:
        if os.path.exists(SAVE_CHATS):
            with open(SAVE_CHATS, "r", encoding="utf-8") as f:
                data = json.load(f)
                return data if isinstance(data, dict) else {}
    except Exception:
        pass
    return {}

def save_chats():
    try:
        with open(SAVE_CHATS, "w", encoding="utf-8") as f:
            json.dump(st.session_state.chats, f, ensure_ascii=False, indent=2)
    except Exception as e:
        st.warning(f"Couldn't save chats: {e}")

def append_checkin(row: Dict[str, Any]):
    df = pd.DataFrame([row])
    exists = os.path.exists(SAVE_CHECKINS)
    df.to_csv(SAVE_CHECKINS, mode="a", header=not exists, index=False)

def read_checkins() -> pd.DataFrame:
    if os.path.exists(SAVE_CHECKINS):
        try:
            return pd.read_csv(SAVE_CHECKINS)
        except Exception:
            pass
    return pd.DataFrame(columns=[
        "timestamp","date","mood","emotion","confidence","journal","response"
    ])

# --------------------------- Safety / Crisis Check ---------------------------
def is_crisis(text: str) -> bool:
    t = text.lower()
    return any(phrase in t for phrase in CRISIS_PHRASES)

def safe_support_reply(user_text: str, emotion: str, history: List[Dict[str,str]], model: str) -> str:
    if is_crisis(user_text):
        # Crisis-forward response (no quotes, no minimization)
        crisis_msg = (
            "I'm really sorry you're feeling this way. You deserve immediate support. "
            "If you are in danger or considering harming yourself, please contact help right now.\n\n"
            + RESOURCES +
            "\n\nIf you want, we can also talk about one small grounding step (e.g., 4-7-8 breathing, "
            "holding ice, naming five things you see). You're not alone."
        )
        return crisis_msg

    sys = (
        "You assist with daily mental health check-ins. Acknowledge the feeling, give EXACTLY one practical step, "
        "and include ONE short verse reference only (e.g., 'Qur’an 94:5', 'Psalm 34:18', 'Bhagavad Gita 2.47'). "
        "Keep the reply under 100 words. Be warm, specific, and non-clinical."
    )
    msgs = [{"role":"system","content": sys}]
    # brief history context (last 4 turns)
    msgs += history[-4:]
    msgs.append({"role":"user","content": f"Emotion: {emotion}\nJournal: {user_text}"})
    return llm_chat(msgs, model=model, max_tokens=180, temperature=0.7, top_p=0.9)

with st.sidebar:
    st.subheader("Settings")
    model_choice = st.selectbox(
        "Model",
        [
            "meta-llama/Llama-3.3-70B-Instruct-Turbo",
            "meta-llama/Llama-3.3-70B-Instruct-Turbo-Free",
        ],
        index=0,
    )


if "chats" not in st.session_state:
    st.session_state.chats = load_chats()

if "current_chat_id" not in st.session_state:
    if st.session_state.chats:
        st.session_state.current_chat_id = next(iter(st.session_state.chats))
    else:
        cid = str(uuid4())
        st.session_state.chats[cid] = {
            "title": "Chat 1",
            "created_at": datetime.utcnow().isoformat(),
            "messages": []
        }
        st.session_state.current_chat_id = cid

def current_chat() -> Dict[str, Any]:
    return st.session_state.chats[st.session_state.current_chat_id]

with st.sidebar:
    st.subheader("Conversations")
    chat_ids = list(st.session_state.chats.keys())
    def _fmt(cid): return st.session_state.chats[cid].get("title", cid)
    idx = chat_ids.index(st.session_state.current_chat_id)
    selected = st.selectbox("Select chat", options=chat_ids, index=idx, format_func=_fmt)
    if selected != st.session_state.current_chat_id:
        st.session_state.current_chat_id = selected
        st.experimental_rerun()

    col1, col2 = st.columns(2)
    with col1:
        if st.button("➕ New chat"):
            cid = str(uuid4())
            st.session_state.chats[cid] = {
                "title": f"Chat {len(st.session_state.chats)+1}",
                "created_at": datetime.utcnow().isoformat(),
                "messages": []
            }
            st.session_state.current_chat_id = cid
            save_chats()
            st.experimental_rerun()
    with col2:
        if st.button("🗑️ Delete chat"):
            del st.session_state.chats[st.session_state.current_chat_id]
            if st.session_state.chats:
                st.session_state.current_chat_id = next(iter(st.session_state.chats))
            else:
                cid = str(uuid4())
                st.session_state.chats[cid] = {"title": "Chat 1", "created_at": datetime.utcnow().isoformat(), "messages": []}
                st.session_state.current_chat_id = cid
            save_chats()
            st.experimental_rerun()

    new_title = st.text_input("Rename current chat", value=current_chat().get("title","Untitled"))
    if new_title and new_title != current_chat().get("title"):
        current_chat()["title"] = new_title
        save_chats()

tab1, tab2, tab3 = st.tabs(["🌅 Daily Check-in", "💬 Open Chat", "🗂️ History"])

with tab1:
    st.subheader("Daily Check-in")

    mood = st.select_slider(
        "How are you feeling right now?",
        options=["😢", "🙁", "😐", "🙂", "😀"],
        value="😐",
        help="A quick mood snapshot for today"
    )
    journal = st.text_area("What's on your mind today?", height=140, placeholder="Type a few sentences...")

    c1, c2, c3 = st.columns([1,1,2])
    with c1:
        do_reply = st.button("Start conversation", type="primary")
    with c2:
        do_clear = st.button("Clear")

    if do_clear:
        journal = ""
        st.experimental_rerun()

    if do_reply and journal.strip():

        emo, conf, scores = detect_emotion_9(journal)

        history = [{"role": m["role"], "content": m["content"]} for m in current_chat()["messages"][-6:]]

        reply = safe_support_reply(journal, emo, history, model_choice)


        with st.chat_message("user"):
            st.markdown(journal)
        with st.chat_message("assistant"):
            st.markdown(f"**Detected emotion:** {emo} ({conf:.2f})\n\n{reply}")

        current_chat()["messages"].append({"role": "user", "content": journal})
        current_chat()["messages"].append({"role": "assistant", "content": f"Detected emotion: {emo} ({conf:.2f})\n\n{reply}"})
        save_chats()


        append_checkin({
            "timestamp": datetime.utcnow().isoformat(),
            "date": date.today().isoformat(),
            "mood": mood,
            "emotion": emo,
            "confidence": round(conf, 4),
            "journal": journal,
            "response": reply,
        })

        with st.expander("Show emotion scores"):
            st.dataframe(pd.DataFrame.from_dict(scores, orient="index", columns=["score"]).sort_values("score", ascending=False))

with tab2:
    st.subheader(current_chat().get("title","Chat"))

    for m in current_chat()["messages"]:
        with st.chat_message("user" if m["role"]=="user" else "assistant"):
            st.markdown(m["content"])


    if not current_chat()["messages"]:
        st.info("Try a quick starter: *“I feel anxious about tomorrow’s meeting.”*, *“Today I’m grateful for…”*, or *“I can’t focus lately.”*")

    user_prompt = st.chat_input("Type your message")
    if user_prompt:

        current_chat()["messages"].append({"role": "user", "content": user_prompt})
        with st.chat_message("user"):
            st.markdown(user_prompt)


        emo, conf, _ = detect_emotion_9(user_prompt)

        hist = [{"role": m["role"], "content": m["content"]} for m in current_chat()["messages"][-6:]]
        reply = safe_support_reply(user_prompt, emo, hist, model_choice)
        assistant_text = f"Detected emotion: {emo} ({conf:.2f})\n\n{reply}"

        with st.chat_message("assistant"):
            st.markdown(assistant_text)

        current_chat()["messages"].append({"role": "assistant", "content": assistant_text})
        save_chats()

with tab3:
    st.subheader("Journal History")
    df = read_checkins()
    if df.empty:
        st.write("No check-ins yet. Use the **Daily Check-in** tab to start.")
    else:
        # Filters
        col_a, col_b = st.columns(2)
        with col_a:
            date_filter = st.date_input("Filter by date", value=None)
        with col_b:
            emotion_filter = st.multiselect("Filter by emotion", options=sorted(df["emotion"].unique()))

        view = df.copy()
        if date_filter:
            view = view[view["date"] == date_filter.isoformat()]
        if emotion_filter:
            view = view[view["emotion"].isin(emotion_filter)]

        view = view.sort_values("timestamp", ascending=False)
        st.dataframe(
            view[["date","mood","emotion","confidence","journal","response"]],
            use_container_width=True, height=420
        )


st.markdown(
    "<hr><small><em>This chatbot provides supportive conversation, not medical advice. "
    "If you’re in crisis or thinking of self-harm, please use the resources above and seek immediate help.</em></small>",
    unsafe_allow_html=True,
)

import os, json, time, random, gc
from uuid import uuid4
from datetime import datetime, date
from typing import List, Dict, Any

def detect_emotion_9(text: str):
    x = tokenizer(
    text,
    return_tensors="pt",
    truncation=True,
    padding="max_length",
    max_length=256,
)

    with torch.no_grad():
        logits = emotion_model(**x).logits
    p = expit(logits.detach().cpu().numpy()[0])
    scores = {g: float(sum(p[i] for i in idxs)) for g, idxs in group_index_map.items()}
    total = sum(scores.values()) or 1.0
    scores = {k: v / total for k, v in scores.items()}
    top = max(scores, key(scores.get))
    return top, scores[top], scores

import gc, os, time, random
import torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification
from together import Together


for name in [
    "emotion_labels", "detect_emotion", "detect_emotion_4",
    "tokenizer", "emotion_model", "group_index_map",
    "detect_emotion_9"
]:
    if name in globals():
        del globals()[name]
gc.collect()


MODEL_NAME = "SamLowe/roberta-base-go_emotions"
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
emotion_model = AutoModelForSequenceClassification.from_pretrained(MODEL_NAME)

if isinstance(emotion_model.config.id2label, dict):
    id2label = {int(k): v for k, v in emotion_model.config.id2label.items()}
else:
    id2label = {i: l for i, l in enumerate(emotion_model.config.id2label)}

groups = {
    "joy":       {"amusement","excitement","joy","pride","relief","gratitude"},
    "sadness":   {"sadness","grief","disappointment","remorse"},
    "anger":     {"anger","annoyance","disapproval"},
    "fear":      {"fear","nervousness","embarrassment","confusion"},
    "disgust":   {"disgust"},
    "surprise":  {"surprise","realization"},
    "love":      {"love","caring","admiration","approval","desire"},
    "optimism":  {"optimism","curiosity"},
    "neutral":   {"neutral"},
}
group_index_map = {g: [] for g in groups}
for i in range(emotion_model.config.num_labels):
    lab = str(id2label[i]).lower()
    placed = False
    for g, fine in groups.items():
        if lab in fine:
            group_index_map[g].append(i); placed = True; break
    if not placed:
        group_index_map["neutral"].append(i)


def detect_emotion_9(text: str):
    x = tokenizer(text, return_tensors="pt", truncation=True, padding="max_length", max_length=256)
    with torch.no_grad():
        logits = emotion_model(**x).logits
    p = torch.sigmoid(logits)[0].cpu().numpy()

    scores = {g: float(sum(p[i] for i in idxs)) for g, idxs in group_index_map.items()}
    total = sum(scores.values()) or 1.0
    scores = {k: v/total for k, v in scores.items()}
    top = max(scores, key=scores.get)
    return top, scores[top], scores

def detect_emotion(text: str):
    label, prob, _ = detect_emotion_9(text)
    return label, prob

print("Detector ready:", emotion_model.config.num_labels, "labels → 9 macros:", sorted(groups.keys()))

import os, time, random
from together import Together

if not os.environ.get("TOGETHER_API_KEY"):
    from getpass import getpass
    os.environ["TOGETHER_API_KEY"] = getpass("199e591c96be5fa613471d111e8765917aee783f05f7a49ba16122b5cfb60ae2 (hidden): ").strip()

client = Together(api_key=os.environ["TOGETHER_API_KEY"])

def generate_response_together(user_input: str, emotion: str) -> str:
    prompt = f"""You are a compassionate mental health journaling assistant.

User is feeling: {emotion}
Their journal entry: "{user_input}"

Please respond with:
- A warm, empathetic message
- A short verse reference only (e.g., "Qur’an 94:5", "Psalm 34:18", "Bhagavad Gita 2.47")
- Exactly one practical, calming suggestion
- Keep the whole reply under 100 words.
""".strip()
    for attempt in range(5):
        try:
            resp = client.chat.completions.create(
                model="meta-llama/Llama-3.3-70B-Instruct-Turbo",  # or ...-Turbo-Free
                messages=[{"role": "user", "content": prompt}],
                max_tokens=180, temperature=0.7, top_p=0.9,
            )
            return resp.choices[0].message.content.strip()
        except Exception as e:
            if "429" in str(e) or "RateLimit" in str(e) or "temporarily unavailable" in str(e):
                time.sleep((2 ** attempt) + random.uniform(0, 0.5)); continue
            raise



inputs = [
    "I feel completely broken and alone today.",
    "I'm so excited to start this new chapter!",
    "I'm just tired of pretending everything is okay.",
    "What a peaceful and lovely evening!",
    "Nobody cares about me."
]

for journal in inputs:
    emotion, prob = detect_emotion(journal)
    reply = generate_response_together(journal, emotion)
    print(f" Journal: {journal}")
    print(f" Detected Emotion: {emotion} ({prob:.2f})")
    print(f" Chatbot Reply:\n{reply}\n{'-'*80}")



